### ISSUE TITLE
0.0.14 -> 1.x changelog, update guide, breaking changes?

### ISSUE THREAD

**Issue by burabure** [clover/remote-pay-cloud#14]
We need some information to upgrade this in a safe manner

**Comment by mike-clover-com** [comment]
Hi Nicolas,
Version 1.x is a significant change from the BETA version (as I am sure you have noticed).   The upgrade path will involve adapting to the improved architecture.  Currently, the [BETA](https://github.com/clover/remote-pay-cloud-BETA/tree/BETA_Final) is still operational, but it will be retired in the future.

The new architecture and design of the library involve the javascript "require()" concept that allows the import of modules.  This should be understood fully, with how it relates to browsers,as well as [NPM](https://www.npmjs.com/).

There are currently three examples that make use of the library available.  
- ["Example React UI to connect to a clover device"](https://github.com/clover/remote-pay-cloud-connector-configuration-react) - this is a [React](https://facebook.github.io/react/) module that can be used to connect to a clover device, both to verify that it is reachable, and to then store the configuration for later use.
- ["Example Manual Transaction Application"](https://github.com/clover/clover-cloud-connector-example) - this shows how the  ["Example React UI to connect to a clover device"](https://github.com/clover/remote-pay-cloud-connector-configuration-react) can be used, and shows how a sale or refund can be performed.  This is also a [React](https://facebook.github.io/react/) module.
- ["Clover Unit Examples Application"](https://github.com/clover/clover-cloud-connector-unit-examples) - this application is similar to the BETA.  It is used to show very small examples of the library; the `sale` operation, the `auth` operation, and others.  It will continue to be expanded with additional tests/examples that can be found in the [public](https://github.com/clover/clover-cloud-connector-unit-examples/tree/master/public) directory.

Both of the applications include instructions on how to run locally, or to run on a Heroku instance.

The core capability has not changed, but the API has been changed to more closely align with our [other SDKs](https://www.clover.com/integrations) and common Javascript coding standards.

Please feel free to ask any additional questions [here on the Clover DevAsk site](https://devask.clover.com).  You may get more immediate feedback there.
