### ISSUE TITLE
Unhandled error when using unescaped special characters in friendly id

### ISSUE THREAD

**Issue by DyegoCosta** [clover/remote-pay-cloud#142]
To reproduce, basically add an unescaped character like `#` to the CloverConnector's `friendlyId`.

<img width="1890" alt="screenshot 2018-04-19 16 37 19" src="https://user-images.githubusercontent.com/636899/39068972-8ef5fac0-44b4-11e8-83bb-1153e4c4702c.png">

Missing a call to `encodeURIComponent` when building the WS address.

**Comment by david-clover-com** [comment]
Thanks @DyegoCosta.

**Comment by david-clover-com** [comment]
This has been fixed in the 3.0.1 release.
