### ISSUE TITLE
What heartbeatInterval and reconnectDelay do?

### ISSUE THREAD

**Issue by DyegoCosta** [clover/remote-pay-cloud#144]
From the docs https://docs.clover.com/build/getting-started-with-cloverconnector/?sdk=browser

```
heartbeatInterval – How long to wait for a PING before disconnecting, in milliseconds.
reconnectDelay – How long to wait before attempting to reconnect, in milliseconds.
```

I'd expect those to be params to configure a connection health check but I couldn't find where it's being used or what difference do they make.

**Comment by david-clover-com** [comment]
Hi @DyegoCosta, reconnectDelay is currently used in the SDK.  It represents the interval (in millis) in which we will attempt to re-establish a connection to the device once it has been lost.  Your expectation of heartbeatInterval matches what it was designed to do.  Unfortunately, the idea was wired through the SDK but never implemented.  The good news is that I noticed this several months ago and a change will be coming in 2.0 which will enable this.  In 2.0, heartbeatInterval will represent an interval (in millis) in which we will ping the device.  If a PONG is not received from the device within a set time (currently 3000 and not configurable - but we could make it so) the websocket will be closed.  This will trigger the corresponding handlers within the Clover Connector so the POS can be notified, and start the reconnection loop (reconnectDelay).

**Comment by DyegoCosta** [comment]
Great to hear @david-clover-com, thanks!

Will the SDK reconnect automatically when possible then? And, is there any estimation of when 2.0 will be release?

Thanks!

**Comment by david-clover-com** [comment]
Yes it will.  No, sorry I do not have a date for this yet.
