### ISSUE TITLE
Server's SHUTDOWN apparently not being handled properly by the SDK

### ISSUE THREAD

**Issue by DyegoCosta** [clover/remote-pay-cloud#145]
We've been facing a situation when we can't connect to the Clover Mini without `forceConnect`, it claims a device is connected to it while apparently there isn't.

After digging the logs I found a strange `SHUTDOWN` command that seems to be coming from the server. Notice the `onMessage` instead of `Sending`.

```
onMessage: {"method":"SHUTDOWN","packageName":"com.clover.remote.protocol.websocket","payload":"{\"method\":\"SHUTDOWN"}"}
```

Right after I see

```
Error processing message: undefined
```

I traced back this message to [here](https://github.com/clover/remote-pay-cloud/blob/318f4de9c14f3953dbb011c0bf98e5217c96c8b9/src/com/clover/remote/client/device/WebsocketCloudCloverDevice.ts#L86), then I noticed that I'm on the SDK `1.4.2` and [the handling of that message](https://github.com/clover/remote-pay-cloud/blob/318f4de9c14f3953dbb011c0bf98e5217c96c8b9/src/com/clover/remote/client/device/WebsocketCloudCloverDevice.ts#L78) was only added to `1.4.3`.

By looking at [what that message handling does](https://github.com/clover/remote-pay-cloud/blob/df783ade6d98c73a54468990f50c7c593659c9d1/src/com/clover/remote/client/transport/websocket/WebSocketCloverTransport.ts#L193) it seems to me that the client was supposed to close the connection of the WS when receive that message, which is not happening on `1.4.2` and it seems to be causing problems on our end (leaving a connection open and not letting other instance connect, we don't currently use `forceConnect`).

I'll update to `1.4.3` and see it the problem gets resolved.

**Comment by david-clover-com** [comment]
Hi @DyegoCosta, I assume you are seeing this when you 4 finger exit from Cloud Pay Display?  Cloud Pay Display was recently modified to send a SHUTDOWN message when the application has been destroyed (4 finger exit, etc.).  You are correct, since this is a new message it was not handled in older versions of the SDK.

**Comment by DyegoCosta** [comment]
Hi @david-clover-com It was only today that I notice that the server was sending the SHUTDOWN and now by using the 4 finger exit to trigger it I was able to simulate a couple of major issues we've been having for the past few weeks (on `1.4.2`).

One of them is that after closing the app while displaying an order when I then try to `initializeConnection` I'll get a `onDeviceConnected` but never a `onDeviceReady`, it will just hang forever, I had to add a `setTimeout` to handle it since it doesn't call any callback that I had implemented.

Updating to `1.4.3` helps with the problem because it's now closing the WS however there's still an issue (or maybe not, let me know) which is that no callback is called, so the connection with the device is severed but the CloverConnector think it's still connected therefore my next attempt to run a sale will hang forever until I refresh the page (which dispose the connector) and start over (create a new connector).

Is there any callback I'm missing to react to that server's `SHUTDOWN`?

**Comment by david-clover-com** [comment]
A handler should be called, try disconnect, I will verify that tomorrow (on my mobile now).  This may be an issue in your testing, but in the real world it would be out of the norm for users to kill CPD.  Are you finding this not to be the case?

**Comment by DyegoCosta** [comment]
@david-clover-com indeed the `onDeviceDisconnected` gets called (testing on remote-pay-cloud-examples), there was probably something wrong with my previous test then I'll try again tomorrow on my project. Thanks!

I'm not sure if our users are closing the CPD on purpose (I wouldn't expect so) or if the SHUTDOWN is coming from the server for another reason, is there anyway to know what triggered that command?

**Comment by david-clover-com** [comment]
The server doesn't send shutdown messages.  It is only sent when the app is disposed, which generally would happen via a 4 finger exit.

**Comment by DyegoCosta** [comment]
I believe I have all the info I need now, thanks a lot @david-clover-com .

Just FYI, if I dispose the connector on onDeviceDisconnected there's an unhandled exception ~~that gets swallowed~~:

<img width="1304" alt="screenshot 2018-05-16 12 57 47" src="https://user-images.githubusercontent.com/636899/40128758-ce86f73a-5908-11e8-9163-03faaca8f9de.png">

<img width="1178" alt="screenshot 2018-05-16 12 58 06" src="https://user-images.githubusercontent.com/636899/40128764-d587e7d8-5908-11e8-94b1-62c43bcb4b21.png">
