### ISSUE TITLE
Long wait between onDeviceConnected and onDeviceReady

### ISSUE THREAD

**Issue by DyegoCosta** [clover/remote-pay-cloud#146]
Give the fact Clover used to sometimes never respond after a `onDeviceConnected` we implemented a timeout that will error out and reattempt to connect if the `onDeviceReady` is not called after a 5 seconds wait after `onDeviceConnected` being called.

We've noticed a increase of that timeout after July 11th, and over this weekend and today this problem affected all of our merchants to some extent, while nothing changed on our code base or the merchant infrastructure; also no reported problem on the ISP.

Can you tell if Clover has noticed any network issue from that date on?

**Comment by DyegoCosta** [comment]
I need to re-open this because it's an on going issue probably since we first integrated with Clover. There's seems to be some flakyness on Clover's proxy servers that constantly stop responding.

I previously closed this issue because on the date I was referring to Clover was apparently in fact having issues on their server.

We notice that very commonly the clover SDK would just hang indefinitely after we attempt to start a new connection to a Clover Mini and because of that we had to implement our own timeout logic, here's the 2 scenario the timeout is most reached and apparently there nothing we can do to avoid it:

## Scenario 1: onDeviceReady never called
1. We call `initializeConnection()` on the Connector
1. We receive the callback `onDeviceConnected()`
1. We wait 10 seconds (timeout) <- At some point increasing the timeout this much helped, after several seconds Clover would respond.
1. `onDeviceReady` or `onDeviceError` are never called

## Scenario 2: onRetrieveDeviceStatusResponse is never called
1. We call `initializeConnection()` on the Connector
1. We receive the callback `onDeviceConnected()`
1. We receive the callback `onDeviceReady()`
1. We start pooling for the device status with `retrieveDeviceStatus()`
1. We call this function 20 times with a interval of 500ms before giving up
1. We error out because we've faced problems that was caused by continue with the transaction without have received the device status response.

Is there any known issue that could be causing this? Anything we can do to avoid it?

Those issues happen hundreds of times a day across many merchants.

cc @david-clover-com

**Comment by david-clover-com** [comment]
Hi @DyegoCosta, under what conditions does your system establish a connection with the Clover device?  Do you still establish a connection per transaction?

**Comment by DyegoCosta** [comment]
@david-clover-com No, we establish only on the first time the user attempt to make a sale. Then that connection is stored and re-used on the next transactions.

**Comment by david-clover-com** [comment]
Ok good.   Do you ever experience this during development/testing?  If so, can you provide me with a scaled down example that can reproduce the problem?  Is the information provided from merchant reports or log analysis?

**Comment by DyegoCosta** [comment]
It's really frustrating "trying" to reproduce this, I basically make a request to Clover and never get a response. It's simple as that. Can you check Clover's servers logs and see those requests and why they are not being replied? I was told once via email that Clover doesn't keep track of those logs which is mind blowing, but it was a long time ago so maybe something changed?

Bottle line I can't reproduce it locally unless I turn off my internet to "simulate a response that never arrives" but the merchant networks are stable and they do not experience any disruption with any other part of the system except for this network call. Also, if the problem is on the proxy server there wouldn't be a way to reproduce it on the sandbox environment. 

Both merchant reports and log analysis, we can clearly see how many times this happens and we constantly are contacted by merchants with reports related to the unresponsiveness of the device until it times out in this exact situations.

**Comment by david-clover-com** [comment]
We do capture logs, but I need some time frames and MIDs to focus my
search.  The same proxy server is deployed to the sandbox environment.

**Comment by DyegoCosta** [comment]
Awesome, I'll send you all the info I've got!
