### ISSUE TITLE
Wrong error about already connected friendlyId

### ISSUE THREAD

**Issue by DyegoCosta** [clover/remote-pay-cloud#147]
https://github.com/clover/remote-pay-cloud/blob/bc1bc6fec041484b9fcfee8d2665a4fd0a654c3e/src/com/clover/remote/client/transport/websocket/WebSocketCloudCloverTransport.ts#L173

I believe this was supposed to be the `connectedId` instead of `friendlyId`

**Comment by david-clover-com** [comment]
@DyegoCosta, you are right.  I noticed this as well and already have a fix in for it.  You will see it in 2.0.

**Comment by DyegoCosta** [comment]
@david-clover-com it recently became really important to us to get the correct id from that error. Any chance this can be released in a smaller patch?

**Comment by david-clover-com** [comment]
@DyegoCosta, this will be our number one priority after we get a 2.0 release out.

**Comment by DyegoCosta** [comment]
Thanks!

**Comment by david-clover-com** [comment]
This is fixed in the 3.0.1 release.
