### ISSUE TITLE
Would this SDK work in react-native?

### ISSUE THREAD

**Issue by aecorredor** [clover/remote-pay-cloud#148]
Or does it have any browser or node specific code?

**Comment by david-clover-com** [comment]
Yes, the SDK should work fine in react-native.  However, the SDK does require a websocket implementation (required for the cloud and network protocols) and an XMLHttpRequest implementation (required for the cloud protocol only).  By default it is assumed that the browser provides these implementations, but custom implementations can be injected into the SDK via the configuration constructors.  Please see our [Node.js example](https://github.com/clover/remote-pay-cloud-examples/tree/master/remote-pay-cloud-nodejs-example) for a bit more information on how this can be accomplished.
