### ISSUE TITLE
Can I use it with ionic 3 - cordova app?

### ISSUE THREAD

**Issue by adityasharma7** [clover/remote-pay-cloud#157]

**Comment by david-clover-com** [comment]
Github issues is not the correct place to ask questions.  We have a community forum - https://community.clover.com/spaces/11/index.html, or you can contact semi-integrations@clover.com.   I have never heard of someone using Ionic and it is not officially supported.  The SDK requires a websocket implementation and a few other things that are provided by a web browser.  It may work however if you follow an integration pattern similar to Node, see a simple example and read the README here - https://github.com/clover/remote-pay-cloud-examples/tree/master/remote-pay-cloud-nodejs-example.

**Comment by adityasharma7** [comment]
Thanks @david-clover-com for your help!
I will use forum only for any further queries.
