### ISSUE TITLE
Consider switching away from prototype

### ISSUE THREAD

**Issue by firedev** [clover/remote-pay-cloud#16]
Please consider switching from `prototype` as it seems it is not intended to for the browser. 

When you `require('prototype')` it blindly overwrites functions in Array and whatnot as described in https://github.com/Rixius/prototype.node.js/issues/8

It would be great if you required the needed functions directly from `lodash/*` or used a similar implementation that does not pollute the global scope.

Thanks.

**Comment by mike-clover-com** [comment]
Resolved via https://github.com/clover/remote-pay-cloud/pull/23
