### ISSUE TITLE
onDeviceDisconnected doesn't seem to fire on device power off

### ISSUE THREAD

**Issue by thoughtspacewebsites** [clover/remote-pay-cloud#179]
Using SNPD app, if I exit the app on the clover device, onDeviceDisconnected fires and allows me to update my UI to show a disconnected Clover device. If I have a connection up, however, and I just power off the Clover Flex device, onDeviceDisconnected doesn't seem to fire. Is this a bug, or is there possibly another listener I missed for power off? Couldn't see anything anywhere...

**Comment by david-clover-com** [comment]
Can you share your connection configuration?  In order for onDeviceDisconnected to fire you need to have heartbeats enabled.  Please try setting heartbeatInterval on the connection configuration builder. You can ask additional questions on our community site - https://community.clover.com/index.html.

**Comment by thoughtspacewebsites** [comment]
Following the steps here:
https://docs.clover.com/docs/cloud-sdk-v3#
onDeviceDisconnected fires just fine in certain circumstances (exiting the app), it just doesn't seem to fire on power off directly from the SNPD app

**Comment by thoughtspacewebsites** [comment]
Closed?

**Comment by thoughtspacewebsites** [comment]
Here's my exact code as it sits moved over to a Vue.JS plugin, but it's pretty direct from the Clover guide with minor modifications to fit within Vue and make it accessable from my other components.
https://gist.github.com/thoughtspacewebsites/8832681a0ac8c383db0b6992adb560fd

**Comment by david-clover-com** [comment]
I can't see your code, can you make it public?  But, as I said above, you need to set a heartbeat interval on the connection configuration.  This will enable a ping/pong which will accurately report disconnects.

**Comment by thoughtspacewebsites** [comment]
Sorry, I updated the comment with a new link, if you clicked it from your email it was likely the old link. Here's the new one again for reference:
https://gist.github.com/thoughtspacewebsites/8832681a0ac8c383db0b6992adb560fd

**Comment by thoughtspacewebsites** [comment]
The "ping pong" seems to be running considering it's reporting disconnect in certain circumstances, and if I watch console logs, I can see a reconnect attempt firing off every X seconds. That said I can certainly still manually configure one if it's truly necessary. Maybe worth updating the "in the cloud" page on the clover site with this too if necessary, as that's the "beginner guider" that I kept getting pointed to everywhere.

**Comment by david-clover-com** [comment]
Certain scenarios will result in a disconnect, certain scenarios won't (FYI - https://bugs.chromium.org/p/chromium/issues/detail?id=706002).  Unless the ping/pong is enabled the SDK won't be able to detect all disconnects.  Looking at your code the ping/pong is disabled (default). Please set the heartbeatInterval and you should be good - https://clover.github.io/remote-pay-cloud/4.0.3/classes/_remote_client_device_websocketcloudcloverdeviceconfiguration_.websocketcloudcloverdeviceconfiguration.html.  `Optional heartbeatInterval: number
Frequency at which we will ping the device - millis. Defaults to -1, which means the heartbeat check is disabled.`

**Comment by thoughtspacewebsites** [comment]
Just following up to say that I set a heartbeatinterval per your recommendation and my issues did indeed clear up. Thanks!

**Comment by david-clover-com** [comment]
Thank you.
