### ISSUE TITLE
1.2.0 Changelog

### ISSUE THREAD

**Issue by burabure** [clover/remote-pay-cloud#39]
I'm noticing some stuff was dropped from 1.1.0 -> 1.2.0, for example the remote-pay-cloud no longer exports VoidReason.

We really need changelogs, is really scary to try to keep the payment gateway up to date when stuff silently change and move around.

**Comment by mike-clover-com** [comment]
Hi, we are working actively to improve our documentation.  The VoidReason is available in the remote-pay-cloud inside the remote-pay-cloud-api.

For example:

```
import * as sdk from 'remote-pay-cloud-api';
import * as Clover from 'remote-pay-cloud';

console.log("VoidReason.USER_CANCEL is " + sdk.order.VoidReason.USER_CANCEL);
console.log("VoidReason.USER_CANCEL is " + Clover.order.VoidReason.USER_CANCEL);
```
