### ISSUE TITLE
README Shows Examples for Legacy Cloud Connector

### ISSUE THREAD

**Issue by TheNorthEestern** [clover/remote-pay-cloud#41]
The README should be updated to reflect changes to the cloud connector API in v1.2.0. I only learned that I was using an outdated version of the connector [through conversations on community.clover.com](https://community.clover.com/questions/9129/retrieving-an-auth-token-for-remote-pay-cloud.html?childToView=9145#answer-9145)

**Comment by mike-clover-com** [comment]
Hi, the readme was changed for 1.2.0.  We did attempt to make the changes clear, we are sorry it was not complete enough.

Version 1.3 is upcoming soon.  Do you have a suggestion as to an addition that should be made to the readme?
