### ISSUE TITLE
CloverConnector.removeCloverConnectorListener adding empty array to listeners list

### ISSUE THREAD

**Issue by DyegoCosta** [clover/remote-pay-cloud#95]
https://github.com/clover/remote-pay-cloud/blob/182af4a9dac31a3ac96a561f0cf294d31a41d532/src/com/clover/remote/client/CloverConnectorBroadcaster.ts#L38-L40

Looks like each time we remove a listener from a clover connector it gets replaced by an empty array which cause the following errors:

![image](https://user-images.githubusercontent.com/636899/31726905-ed6f7200-b406-11e7-917c-2eb734d75bef.png)

**Comment by david-clover-com** [comment]
Thanks for the report @DyegoCosta.  I will get this resolved for the next release.

**Comment by david-clover-com** [comment]
The fix for this has been merged into develop and will be available in 1.4.2.

**Comment by mike-clover-com** [comment]
Release 1.4.2 is now available.
